name: CI/CD

on:
  push:
    branches:
      - 'https://github.com/sergeymolod/test_python_advanced'
  pull_request:
    branches:
      - 'https://github.com/sergeymolod/test_python_advanced'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black mypy

      - name: Run flake8
        run: |
          flake8 . --max-line-length=88

      - name: Run isort
        run: |
          isort . --check --diff

      - name: Run black --check
        run: |
          black --check .

      - name: Run mypy
        run: |
          mypy .
